force-app/main/default/objects/Sensor__c/Sensor__c.object-meta.xml
<CustomObject>
    <label>Sensor</label>
    <nameField>
        <label>Sensor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sensors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/Sensor_Event__c.object-meta.xml
<CustomObject>
    <label>Sensor Event</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Sensor Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sensor Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Sensor_Event__c/fields/Sensor__c.field-meta.xml
<CustomField>
    <fullName>Sensor__c</fullName>
    <label>Sensor</label>
    <referenceTo>Sensor__c</referenceTo>
    <relationshipLabel>Sensor Events</relationshipLabel>
    <relationshipName>Sensor_Events</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SensorServiceTest.cls
@IsTest
public class SensorServiceTest {

    @TestSetup
    static void makeData(){
        Sensor__c sensor = new Sensor__c(Name = '200');
        insert sensor;
    }

    @isTest
    public static void postServiceData() {

        List<Integer> line = new List<Integer>();
        for(Integer i = 0; i < 24; i++) {
            line.add(i);
        }
        SensorServiceData sensorData = new SensorServiceData('100', line);

        SensorService.putData(JSON.serialize(sensorData));

        List<Sensor_Event__c> events = [SELECT Name FROM Sensor_Event__c];

        System.assertEquals(line.size() / 3, events.size(), 'Actual amount of sensor events does n\' equal to expected');

    }

    @isTest
    public static void postServiceDataWithExistsSensor() {

        List<Integer> line = new List<Integer>();
        for(Integer i = 0; i < 22; i++) {
            line.add(i);
        }
        SensorServiceData sensorData = new SensorServiceData('200', line);

        SensorService.putData(JSON.serialize(sensorData));

        List<Sensor_Event__c> events = [SELECT Name FROM Sensor_Event__c];

        System.assertEquals(line.size() / 3, events.size(), 'Actual amount of sensor events does n\' equal to expected');

    }
}